[Bot]
#token =
#id
#cache_max_messages
#username = 
#activity =
#ping_message =
#ping_payload = 
#uptime_url =
#uptime_token =
#owner_id =
#error_webhook =
#feedback_webhook =
#lavalink_host = ""
#lavalink_password = ""

[PostgreSQL]
#database = 
#password = 
#host =
#port = 
#user = 
#max_connections = 

[Logging]
#log_level =
#host =
#env =

[Server]
#translate =
#search =
#llm_host_text =
#llm_host_tts =
#llm_host_stt =
#text_model_small =
#text_model_large
#tts_model = 
#stt =

[API-Info]
#gif_url =
#cloudflare_token =
#cloudflare_image_gen = 

[HTTP-Agent]
#title = ""
#repo = ""
#email = ""
