name: Build executable
on:
  workflow_dispatch:
concurrency:
  group: deploy-${{ forgejo.ref }}
  cancel-in-progress: false
jobs:
  build:
    name: Build binary
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - runner: fabsearch-latest-pi
            features: simd-neon
          - runner: fabsearch-latest-arm
            features: simd-neon
          - runner: fabsearch-latest
            features: simd-avx
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup rust
        uses: https://codeberg.org/prjunnamed/setup-rust-toolchain@f0e3fff1ca3442708aa9fb8156820eb859d80846
        with:
          toolchain: nightly-2026-06-13
          components: rust-src
          rustflags: ""
          cache: false
      - name: Cache sccache directory
        uses: actions/cache@v6
        with:
          path: ~/.cache/sccache
          key: sccache-${{ matrix.runner }}-${{ matrix.features }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            sccache-${{ matrix.runner }}-${{ matrix.features }}-
      - name: Build
        run: cargo build --release --features ${{ matrix.features }}
      - name: Upload artifact
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: fabsebot-${{ matrix.runner }}
          path: target/release/fabsebot
