name: Build executable
on:
  workflow_dispatch:
jobs:
  build:
    name: Build binary
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        runner: [fabsearch-latest-pi, fabsearch-latest-vps]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup rust
        uses: https://codeberg.org/prjunnamed/setup-rust-toolchain@f0e3fff1ca3442708aa9fb8156820eb859d80846
        with:
          toolchain: nightly-2026-06-13
          components: rust-src
          rustflags: ""
      - name: Build
        run: cargo build --release
        env:
          CARGO_BUILD_RUSTC_WRAPPER: ""
      - name: Upload artifact
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: fabsebot-${{ matrix.runner }}
          path: target/release/fabsebot
