ALTER TABLE guild_settings
MODIFY dead_chat_channel BIGINT UNSIGNED NULL DEFAULT NULL,
MODIFY dead_chat_rate BIGINT UNSIGNED NULL DEFAULT NULL,
MODIFY quotes_channel BIGINT UNSIGNED NULL DEFAULT NULL,
MODIFY spoiler_channel BIGINT UNSIGNED NULL DEFAULT NULL,
MODIFY prefix CHAR(5) NULL DEFAULT NULL;
