ALTER TABLE user_settings
MODIFY COLUMN message_count INT UNSIGNED NULL DEFAULT 0;

ALTER TABLE guild_settings
MODIFY COLUMN dead_chat_rate INT UNSIGNED NULL DEFAULT NULL;

ALTER TABLE words_count
MODIFY COLUMN count INT UNSIGNED NULL DEFAULT 0;
