[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=--ld-path=wild"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=--ld-path=wild"]

[build]
rustc-wrapper = "sccache"
rustflags = ["-Z", "threads=8"]

[unstable]
gc = true
build-std = ["std", "panic_abort"]
#build-std-features = ["panic_immediate_abort"]
